#!/bin/bash
set -e

EMAIL="releases@kenfos.co.uk"
USER_NAME="CI"

function setup {
  $(eval "git config user.email $EMAIL")
  $(eval "git config user.name $USER_NAME")
}

function set_version {
  local version=$1
  $(eval "lein set-version $version")
  $(eval "git commit -am 'auto lein-release plugin: preparing $version release'")
}

function release {
  local commit_message=$(eval 'git log --oneline -1')
  local version=$(eval "./script/commit-version '$commit_message'")
  if [ -z "$version" ]; then
    set_version $version
  else
    lein release
  fi
  git push
}

function is_master_branch {
  [ "$BRANCH_NAME" == "master" ]
}

function is_release_commit {
  git log --oneline -1 | grep "lein-release plugin"
}

function is_release {
  (is_master_branch) && !(is_release_commit)
}

if is_release; then
  setup
  release
fi
