#!/bin/bash
set -e

EMAIL="releases@kenfos.co.uk"
USER_NAME="CI"

function setup {
  git config user.email $EMAIL
  git config user.name $USER_NAME
}

function set_version {
  local version=$1
  lein set-version $version
  git add project.clj
  git commit -m "'auto release version $version'"
}

function release {
  local commit_message=$(eval 'git log --oneline -1')
  local version=$(eval "./script/commit-version '$commit_message'")
  if [ -z "$version" ]; then
    lein release
  else
    set_version "$version-SNAPSHOT"
  fi
  git push
}

function is_master_branch {
  [ "$BRANCH_NAME" == "master" ]
}

function is_release_commit {
  git log --oneline -1 | grep "lein-release plugin"
}

function is_release {
  (is_master_branch) && !(is_release_commit)
}

if is_release; then
  setup
  release
fi
