#!/bin/bash
set -e

lein with-profile test test

if [ "$BRANCH_NAME" == "master" ]; then
  lein release

  git config --global user.email "releases@kenfos.co.uk"
  git config --global user.name "CI environment"
  git push
fi
